coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        if_no_uploads: error

    patch:
      default:
        if_no_uploads: error

    changes: true

  ignore:
    - src/lib/befor64.F90
    - src/lib/befor64_pack_data_m.F90
    - src/lib/penf.F90
    - src/lib/stringifor.F90
    - src/lib/stringifor_string_t.F90

comment:
  layout: "header, diff, changes, suggestions"
  behavior: default
